DROP PROCEDURE IF EXISTS CLEAN_TABLES;

DELIMITER /

CREATE PROCEDURE CLEAN_TABLES()
BEGIN
	DROP TABLE IF EXISTS KUNDE;
	DROP TABLE IF EXISTS BESTELLUNG;
	DROP TABLE IF EXISTS REZEPT_BESTELLUNG;
	DROP TABLE IF EXISTS REZEPT;
	DROP TABLE IF EXISTS REZEPT_ZUTAT;
	DROP TABLE IF EXISTS ADRESSE;
	DROP TABLE IF EXISTS LIEFERANT;
	DROP TABLE IF EXISTS ZUTAT;
	DROP TABLE IF EXISTS ZUTAT_BESCHRAENKUNG;
	DROP TABLE IF EXISTS BESCHRAENKUNG;
	DROP TABLE IF EXISTS ZUTAT_ERNAEHRUNGSKATEGORIE;
	DROP TABLE IF EXISTS ERNAEHRUNGSKATEGORIE;
	DROP TABLE IF EXISTS NAEHRSTOFFANGABE;
END; /
DELIMITER ;

CALL CLEAN_TABLES;
