DELIMITER /
DROP PROCEDURE IF EXISTS CREATE_DATABASE; /

CREATE PROCEDURE CREATE_DATABASE()
BEGIN
	DROP DATABASE IF EXISTS BIO_FRESH;
	CREATE DATABASE BIO_FRESH;
END; /

DELIMITER ;
CALL CREATE_DATABASE;
USE BIO_FRESH;