DROP PROCEDURE IF EXISTS CREATE_TABLES;

DELIMITER /

CREATE PROCEDURE CREATE_TABLES ()
BEGIN
	CALL CLEAN_TABLES;
	CALL CREATE_KUNDE;
	CALL CREATE_BESTELLUNG;
	CALL CREATE_REZEPT_BESTELLUNG;
	CALL CREATE_REZEPT;
	CALL CREATE_REZEPT_ZUTAT;
	CALL CREATE_ADRESSE;
	CALL CREATE_LIEFERANT;
	CALL CREATE_ZUTAT;
	CALL CREATE_ZUTAT_BESCHRAENKUNG;
	CALL CREATE_BESCHRAENKUNG;
	CALL CREATE_ZUTAT_ERNAEHRUNGSKATEGORIE;
	CALL CREATE_ERNAEHRUNGSKATEGORIE;
	CALL CREATE_NAEHRSTOFFANGABE;
	CALL ASSIGN_FOREIGN_KEYS;
END; /

DELIMITER ;