DROP PROCEDURE IF EXISTS CREATE_TABLES;

CALL CLEAN_TABLES;

DELIMITER /
CREATE PROCEDURE CREATE_TABLES()
BEGIN
	CALL CREATE_KUNDE;
	CALL CREATE_BESTELLUNG;
	CALL CREATE_REZEPT_BESTELLUNG;
	CALL CREATE_REZEPT;
	CALL CREATE_REZEPT_ZUTAT;
	CALL CREATE_ADRESSE;
	CALL CREATE_LIEFERANT;
	CALL CREATE_ZUTAT;
	CALL CREATE_ZUTAT_BESCHRAENKUNG;
	CALL CREATE_BESCHRAENKUNG;
	CALL CREATE_ZUTAT_ERNAEHRUNGSKATEGORIE;
	CALL CREATE_ERNAEHRUNGSKATEGORIE;
	CALL CREATE_NAEHRSTOFFANGABE;
END; /
DELIMITER ;

CALL CREATE_TABLES;