DROP PROCEDURE IF EXISTS DROP_FOREIGN_KEYS;

DELIMITER /

CREATE PROCEDURE DROP_FOREIGN_KEYS()
BEGIN
	ALTER TABLE KUNDE
		DROP FOREIGN KEY IF EXISTS AdresseId;
			
	ALTER TABLE BESTELLUNG
		DROP FOREIGN KEY IF EXISTS KundeId;
	
	ALTER TABLE REZEPT_BESTELLUNG		
		DROP FOREIGN KEY IF EXISTS BestellungId;
	ALTER TABLE REZEPT_BESTELLUNG
		DROP FOREIGN KEY IF EXISTS RezeptId;
			
	ALTER TABLE REZEPT_ZUTAT
		DROP FOREIGN KEY IF EXISTS RezeptId;
	ALTER TABLE REZEPT_ZUTAT	
		DROP FOREIGN KEY IF EXISTS ZutatId;
	
	ALTER TABLE LIEFERANT
		DROP FOREIGN KEY IF EXISTS AdresseId;
			
	ALTER TABLE ZUTAT
		DROP FOREIGN KEY IF EXISTS LieferantId;
	ALTER TABLE ZUTAT
		DROP FOREIGN KEY IF EXISTS NaehrstoffangabeId;
	
	ALTER TABLE ZUTAT_BESCHRAENKUNG		
		DROP FOREIGN KEY IF EXISTS BeschraenkungId;
	ALTER TABLE ZUTAT_BESCHRAENKUNG	
		DROP FOREIGN KEY IF EXISTS ZutatId;
	
	ALTER TABLE ZUTAT_ERNAEHRUNGSKATEGORIE		
		DROP FOREIGN KEY IF EXISTS ErnaehrungskategorieId;
	ALTER TABLE ZUTAT_ERNAEHRUNGSKATEGORIE		
		DROP FOREIGN KEY IF EXISTS ZutatId;
END; /

DELIMITER ;