DROP PROCEDURE IF EXISTS ASSIGN_FOREIGN_KEYS;

DELIMITER /

CREATE PROCEDURE ASSIGN_FOREIGN_KEYS()
BEGIN
	ALTER TABLE KUNDE
		ADD FOREIGN KEY (AdresseId) 
			REFERENCES ADRESSE (AdresseId);
			
	ALTER TABLE BESTELLUNG
		ADD FOREIGN KEY (KundeId) REFERENCES
			KUNDE (KundeId);
	
	ALTER TABLE REZEPT_BESTELLUNG		
		ADD FOREIGN KEY (BestellungId) REFERENCES
			bestellung (BestellungId);
	ALTER TABLE REZEPT_BESTELLUNG
		ADD FOREIGN KEY (RezeptId) REFERENCES
			REZEPT (RezeptId);
			
	ALTER TABLE REZEPT_ZUTAT
		ADD FOREIGN KEY (RezeptId) REFERENCES
			REZEPT (RezeptId);
	ALTER TABLE REZEPT_ZUTAT	
		ADD FOREIGN KEY (ZutatId) REFERENCES
			ZUTAT (ZutatId);
	
	ALTER TABLE LIEFERANT
		ADD FOREIGN KEY (AdresseId) REFERENCES
			ADRESSE (AdresseId);
			
	ALTER TABLE ZUTAT
		ADD FOREIGN KEY (LieferantId) REFERENCES
			LIEFERANT (LieferantId);
	ALTER TABLE ZUTAT
		ADD FOREIGN KEY (NaehrstoffangabeId) REFERENCES
			NAEHRSTOFFANGABE (NaehrstoffangabeId);
	
	ALTER TABLE CREATE_ZUTAT_BESCHRAENKUNG		
		ADD FOREIGN KEY (BeschraenkungId) REFERENCES
			Beschraenkung (BeschraenkungId);
	ALTER TABLE CREATE_ZUTAT_BESCHRAENKUNG	
		ADD FOREIGN KEY (ZutatId) REFERENCES
			ZUTAT (ZutatId);
	
	ALTER TABLE ZUTAT_ERNAEHRUNGSKATEGORIE		
		ADD FOREIGN KEY (ErnaehrungskategorieId) REFERENCES
			ERNAEHRUNGSKATEGORIE (ErnaehrungskategorieId);
	ALTER TABLE ZUTAT_ERNAEHRUNGSKATEGORIE		
		ADD FOREIGN KEY (ZutatId) REFERENCES
			ZUTAT (ZutatId);
END; /

DELIMITER ;